name: 'Atelier California '
favicon: null
layout_spectrum: 0.99903
typography_spectrum: 0.5179211
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#DBE5E7'
    - '#5F5643'
    - '#9D9A91'
    - '#22180E'
    - '#FA7FCF'
  brandStrength: 0.8688151
  lightness: 1
  saturation: 0.718638
  rhythmicContrast: 0.1523297
purpose: []
