layout_spectrum: 0.827957
color:
  saturation: 1
  brandStrength: 0.8688151
  lightness: 1
  rhythmicContrast: 0.4659498
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
typography_spectrum: 0.5179211
name: 'Atelier California '
