name: 'Atelier California '
favicon: null
layout_spectrum: 0.25097
typography_spectrum: 0.25678
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: ATELIER CALIFORNIA
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#faf9f7'
    - '#c8c7c3'
    - '#9e9f9a'
    - '#000100'
    - '#484b42'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
